// GearCatalog.js — 180 named gear pieces (30 per slot)
// Slots: helm, chest, boot, cloak, vam, ring
// Rarities: common, uncommon, rare, epic, legendary, mythic

'use strict';

const GEAR_CATALOG = [
  {id:'helm_001',name:'Iron Coif',rarity:'common',slot:'helm',desc:'Standard E-rank gear. Stops basic blows.',lore:'Cracked at the rim but never complained.',stats:{"hp": 20, "statusResist": 2},special:null},
  {id:'helm_002',name:'Leather Scout Cap',rarity:'common',slot:'helm',desc:'Light and flexible. Good for running away fast.',lore:'Speed saves more lives than armor.',stats:{"hp": 17, "statusResist": 4},special:null},
  {id:'helm_003',name:'Rookie\'s Helm',rarity:'common',slot:'helm',desc:'Association-issued starter protection.',lore:'The association gives these out for free.',stats:{"hp": 22, "statusResist": 2},special:null},
  {id:'helm_004',name:'Bronze Skullcap',rarity:'common',slot:'helm',desc:'Heavier than leather. Tougher too.',lore:'Took a hit so your skull didn\'t have to.',stats:{"hp": 25, "statusResist": 2},special:null},
  {id:'helm_005',name:'Bone Mask',rarity:'common',slot:'helm',desc:'Fashioned from skeleton-type creature bone.',lore:'Intimidating to those who don\'t know better.',stats:{"hp": 21, "statusResist": 4},special:null},
  {id:'helm_006',name:'Shadow Stalker Hood',rarity:'uncommon',slot:'helm',desc:'Absorbs ambient mana from dark dungeons.',lore:'Worn by hunters who prefer not to be seen.',stats:{"hp": 45, "statusResist": 8},special:null},
  {id:'helm_007',name:'Flame Warden Cap',rarity:'uncommon',slot:'helm',desc:'Fire-treated leather with heat resistance.',lore:'Dungeons run hot. So do the hunters inside them.',stats:{"hp": 46, "statusResist": 8},special:null},
  {id:'helm_008',name:'Runemarked Helm',rarity:'uncommon',slot:'helm',desc:'Ancient runes etched by an unknown hand.',lore:'The meaning lost. The power remains.',stats:{"hp": 49, "statusResist": 8},special:null},
  {id:'helm_009',name:'Vanguard Helm',rarity:'uncommon',slot:'helm',desc:'Reinforced for front-line dungeon combat.',lore:'Someone has to walk in first.',stats:{"hp": 53, "statusResist": 7},special:null},
  {id:'helm_010',name:'Reaper\'s Hood',rarity:'uncommon',slot:'helm',desc:'Black as the void between gates.',lore:'Those who wear this tend to finish raids alone.',stats:{"hp": 49, "statusResist": 10},special:null},
  {id:'helm_011',name:'Dragon Eye Visor',rarity:'rare',slot:'helm',desc:'Crafted from the eye of a dragon-type boss.',lore:'Still sees everything the dragon saw.',stats:{"hp": 80, "statusResist": 15},special:null},
  {id:'helm_012',name:'Igris War Helm',rarity:'rare',slot:'helm',desc:'Modeled after the Shadow Monarch\'s knight.',lore:'To wear it is to carry the weight of loyalty.',stats:{"hp": 88, "statusResist": 14},special:null},
  {id:'helm_013',name:'Cerberus Helm',rarity:'rare',slot:'helm',desc:'Three-faced guard. Watches every direction.',lore:'Nothing gets past all three.',stats:{"hp": 90, "statusResist": 13},special:null},
  {id:'helm_014',name:'Ant King Carapace Helm',rarity:'rare',slot:'helm',desc:'Torn from the Ant King\'s exoskeleton mid-battle.',lore:'He didn\'t give it up easily.',stats:{"hp": 92, "statusResist": 13},special:null},
  {id:'helm_015',name:'Muzan\'s Veil',rarity:'rare',slot:'helm',desc:'Pulsing with demon aura. Unsettling to look at.',lore:'Even demons fear what wears this.',stats:{"hp": 80, "statusResist": 16},special:null},
  {id:'helm_016',name:'Shadow Monarch\'s Circlet',rarity:'epic',slot:'helm',desc:'Worn by high-ranking shadow soldiers.',lore:'The Shadow Monarch\'s army wears this as a mark of service.',stats:{"hp": 140, "statusResist": 25},special:null},
  {id:'helm_017',name:'Six Eyes Hood',rarity:'epic',slot:'helm',desc:'Grants perception of cursed energy flows.',lore:'Some things shouldn\'t be seen. This sees them anyway.',stats:{"hp": 135, "statusResist": 27},special:null},
  {id:'helm_018',name:'Beru\'s Exo Crown',rarity:'epic',slot:'helm',desc:'Carved from the shell of Ant King Beru.',lore:'The strongest ant ever born. His shell remains.',stats:{"hp": 158, "statusResist": 22},special:null},
  {id:'helm_019',name:'Akatsuki War Helm',rarity:'epic',slot:'helm',desc:'Forged in the hidden world. Red cloud motifs.',lore:'The red clouds aren\'t decoration.',stats:{"hp": 150, "statusResist": 24},special:null},
  {id:'helm_020',name:'Titan Nape Guard',rarity:'epic',slot:'helm',desc:'Covers the nape like a second skin.',lore:'Protect what matters most.',stats:{"hp": 155, "statusResist": 23},special:null},
  {id:'helm_021',name:'Igris\'s True Helm',rarity:'legendary',slot:'helm',desc:'The actual helm worn by Igris before his rebirth.',lore:'Loyalty carved in iron.',stats:{"hp": 275, "statusResist": 38},special:{"id": "defBoost", "desc": "+15% DEF when HP drops below 50%"}},
  {id:'helm_022',name:'Susanoo Helm',rarity:'legendary',slot:'helm',desc:'Manifests a faint Susanoo shield when worn.',lore:'The sharingan doesn\'t activate. The protection does.',stats:{"hp": 278, "statusResist": 38},special:{"id": "susanooShield", "desc": "10% chance to fully negate one attack per battle"}},
  {id:'helm_023',name:'Cursed King\'s Crown',rarity:'legendary',slot:'helm',desc:'Bound with the essence of Ryomen Sukuna.',lore:'Twenty fingers. One crown. Infinite malice.',stats:{"hp": 272, "statusResist": 39},special:{"id": "cursedAmplify", "desc": "+12% skill damage on every hit"}},
  {id:'helm_024',name:'Dragon Monarch\'s Helm',rarity:'legendary',slot:'helm',desc:'The Dragon Monarch\'s personal battle crown.',lore:'Dragons bow to whoever wears this.',stats:{"hp": 282, "statusResist": 38},special:{"id": "dragonFear", "desc": "15% chance to inflict Fear on attackers"}},
  {id:'helm_025',name:'Eternal Night Helm',rarity:'legendary',slot:'helm',desc:'Forged during the longest dungeon siege in history.',lore:'The night lasted 40 days. The helm lasted forever.',stats:{"hp": 276, "statusResist": 39},special:{"id": "nightVision", "desc": "Status effects on you last 1 turn less"}},
  {id:'helm_026',name:'Shadow Monarch\'s True Crown',rarity:'mythic',slot:'helm',desc:'Sung Jinwoo\'s crown. The throne of all shadows.',lore:'Every shadow in existence bends to this crown.',stats:{"hp": 500, "statusResist": 70},special:{"id": "shadowDomain", "desc": "Start battle with Shadow Veil \u2014 15% miss chance vs you for 3 turns"}},
  {id:'helm_027',name:'Architect\'s Helm',rarity:'mythic',slot:'helm',desc:'Worn by the Architect who watches all systems.',lore:'He who observes controls. He who controls wins.',stats:{"hp": 480, "statusResist": 72},special:{"id": "systemView", "desc": "See all enemy stats before battle starts"}},
  {id:'helm_028',name:'Absolute Being\'s Fragment',rarity:'mythic',slot:'helm',desc:'A piece of the original divine\'s consciousness.',lore:'Gods don\'t die. They fragment. This is one.',stats:{"hp": 520, "statusResist": 68},special:{"id": "divineWill", "desc": "Survive one fatal hit per battle at 1 HP"}},
  {id:'helm_029',name:'Sukuna\'s Crown',rarity:'mythic',slot:'helm',desc:'The King of Curses\' own crown, reforged for the living.',lore:'A thousand years of malice crystallized.',stats:{"hp": 495, "statusResist": 71},special:{"id": "malevolentShrine", "desc": "Skills deal +20% damage and ignore 15% of enemy DEF"}},
  {id:'helm_030',name:'Void Throne Crown',rarity:'mythic',slot:'helm',desc:'Crown of the being that created the gate system.',lore:'To wear this is to understand why gates exist at all.',stats:{"hp": 550, "statusResist": 65},special:{"id": "voidThrone", "desc": "Gain 50 energy at battle start. Skills cost 20% less energy"}},
  {id:'chest_001',name:'Iron Breastplate',rarity:'common',slot:'chest',desc:'Standard iron armor. Stops basic attacks.',lore:'Good enough to survive the first gate.',stats:{"def": 18, "hp": 15},special:null},
  {id:'chest_002',name:'Leather Vest',rarity:'common',slot:'chest',desc:'Light and flexible dungeon wear.',lore:'Speed over protection. A calculated gamble.',stats:{"def": 14, "hp": 18},special:null},
  {id:'chest_003',name:'Chain Mail Vest',rarity:'common',slot:'chest',desc:'Interlocked rings of dungeon iron.',lore:'Flexible enough to fight in.',stats:{"def": 17, "hp": 15},special:null},
  {id:'chest_004',name:'Padded Jerkin',rarity:'common',slot:'chest',desc:'Multiple layers of dungeon-treated cloth.',lore:'Comfort for the long raids.',stats:{"def": 13, "hp": 20},special:null},
  {id:'chest_005',name:'Stone Scale Vest',rarity:'common',slot:'chest',desc:'Scales from a stone lizard dungeon creature.',lore:'Heavy. Effective. Ugly.',stats:{"def": 21, "hp": 11},special:null},
  {id:'chest_006',name:'Shadow Stalker Coat',rarity:'uncommon',slot:'chest',desc:'Absorbs light passively. Hard to spot in dim areas.',lore:'For hunters the dungeon was never meant to see.',stats:{"def": 35, "hp": 30},special:null},
  {id:'chest_007',name:'Flame Warden Plate',rarity:'uncommon',slot:'chest',desc:'Heat-resistant alloy forged near lava dungeons.',lore:'The heat is just another enemy to manage.',stats:{"def": 37, "hp": 30},special:null},
  {id:'chest_008',name:'Runebound Plate',rarity:'uncommon',slot:'chest',desc:'Ancient runes pulse faintly with mana.',lore:'Someone spent years carving these. Worth every hour.',stats:{"def": 39, "hp": 29},special:null},
  {id:'chest_009',name:'Vanguard Plate',rarity:'uncommon',slot:'chest',desc:'Reinforced at every strike point.',lore:'Takes the first hit so the team doesn\'t have to.',stats:{"def": 43, "hp": 26},special:null},
  {id:'chest_010',name:'Reaper\'s Coat',rarity:'uncommon',slot:'chest',desc:'Jet black. Absorbs dungeon ambient mana.',lore:'You finish raids. Others don\'t.',stats:{"def": 39, "hp": 30},special:null},
  {id:'chest_011',name:'Dragon Scale Plate',rarity:'rare',slot:'chest',desc:'Actual dragon scales fused into reinforced plate.',lore:'To wear a dragon is to inherit its toughness.',stats:{"def": 65, "hp": 55},special:null},
  {id:'chest_012',name:'Igris Black Armor',rarity:'rare',slot:'chest',desc:'Modeled after the Shadow Knight Igris.',lore:'Worn by the best warrior the Shadow Monarch commands.',stats:{"def": 70, "hp": 52},special:null},
  {id:'chest_013',name:'Cerberus Hide Armor',rarity:'rare',slot:'chest',desc:'Made from the three-headed gate guardian.',lore:'Three heads worth of protection in one chest piece.',stats:{"def": 72, "hp": 50},special:null},
  {id:'chest_014',name:'Ant King Shell Plate',rarity:'rare',slot:'chest',desc:'Carved from the Ant King\'s torso exoskeleton.',lore:'The creature that nearly ended humanity. This is what\'s left.',stats:{"def": 74, "hp": 50},special:null},
  {id:'chest_015',name:'Haori of the Pillars',rarity:'rare',slot:'chest',desc:'Modeled after the Hashira uniform. Reinforced inside.',lore:'The design is art. The function is war.',stats:{"def": 64, "hp": 56},special:null},
  {id:'chest_016',name:'Shadow Army Plate',rarity:'epic',slot:'chest',desc:'Standard armor for high-rank shadow soldiers.',lore:'The Shadow Monarch\'s elite don\'t use cheap gear.',stats:{"def": 110, "hp": 95},special:null},
  {id:'chest_017',name:'Infinity Vest',rarity:'epic',slot:'chest',desc:'Reinforced with the defensive principle of Infinity.',lore:'Nothing reaches the body beneath it. In theory.',stats:{"def": 105, "hp": 100},special:null},
  {id:'chest_018',name:'Beru\'s Carapace Plate',rarity:'epic',slot:'chest',desc:'The Ant King Beru\'s torso shell.',lore:'He survived the world\'s strongest raid team for hours.',stats:{"def": 125, "hp": 85},special:null},
  {id:'chest_019',name:'Akatsuki Reinforced Cloak',rarity:'epic',slot:'chest',desc:'The famous red cloud cloak reinforced for battle.',lore:'It\'s a target. It\'s also armor. Both by design.',stats:{"def": 110, "hp": 95},special:null},
  {id:'chest_020',name:'Titan Remnant Plate',rarity:'epic',slot:'chest',desc:'Forged from hardened titan nape material.',lore:'The nape is the weakness. It became the strongest point.',stats:{"def": 122, "hp": 87},special:null},
  {id:'chest_021',name:'Absolute Defense Plate',rarity:'legendary',slot:'chest',desc:'Reduces all incoming physical damage passively.',lore:'The absolute. Not a metaphor.',stats:{"def": 220, "hp": 180},special:{"id": "absoluteShield", "desc": "Reduce physical damage taken by 10%"}},
  {id:'chest_022',name:'Igris\'s True Armor',rarity:'legendary',slot:'chest',desc:'Igris wore this before becoming a shadow soldier.',lore:'Service beyond death. That\'s loyalty.',stats:{"def": 235, "hp": 175},special:{"id": "loyaltyDef", "desc": "+20% DEF when an ally is below 30% HP"}},
  {id:'chest_023',name:'Sukuna\'s Vessel Plate',rarity:'legendary',slot:'chest',desc:'The plate that contained Sukuna\'s vessel.',lore:'It holds things it shouldn\'t be able to hold.',stats:{"def": 228, "hp": 177},special:{"id": "vesselStrength", "desc": "Immune to Weaken and Enfeeble status effects"}},
  {id:'chest_024',name:'Dragon Monarch\'s Plate',rarity:'legendary',slot:'chest',desc:'The Dragon Monarch\'s personal battle armor.',lore:'Dragons bend the battlefield. The armor bends attacks.',stats:{"def": 242, "hp": 171},special:{"id": "dragonScale", "desc": "Reduce all incoming damage by 8%"}},
  {id:'chest_025',name:'National Level Plate',rarity:'legendary',slot:'chest',desc:'Only worn by hunters classified as National Level threats.',lore:'Countries moved their armies. He moved alone.',stats:{"def": 250, "hp": 168},special:{"id": "nationalLevel", "desc": "Reduce all incoming damage by 12% during dungeon raids"}},
  {id:'chest_026',name:'Shadow Monarch\'s True Armor',rarity:'mythic',slot:'chest',desc:'Sung Jinwoo\'s personal battle armor.',lore:'The Monarch of Shadows has no need for protection. He wears it anyway.',stats:{"def": 450, "hp": 380},special:{"id": "monarchPresence", "desc": "Enemies deal 20% less damage to you. Allies take 10% less damage"}},
  {id:'chest_027',name:'Architect\'s Frame',rarity:'mythic',slot:'chest',desc:'The Architect\'s body, rendered as armor.',lore:'A system watching. A body armoring.',stats:{"def": 430, "hp": 395},special:{"id": "systemArmor", "desc": "At battle start: analyze enemy and gain +20% DEF against their dominant attack type"}},
  {id:'chest_028',name:'Absolute Being\'s Vessel',rarity:'mythic',slot:'chest',desc:'Fragment of the divine\'s physical form.',lore:'Gods don\'t need armor. This one made some anyway.',stats:{"def": 470, "hp": 375},special:{"id": "absoluteBeing", "desc": "Immune to one-shot kills. Reduce all damage taken by 20%"}},
  {id:'chest_029',name:'Sukuna\'s True Vessel',rarity:'mythic',slot:'chest',desc:'Ryomen Sukuna\'s actual vessel armor, reforged.',lore:'A thousand curses crammed into solid plate.',stats:{"def": 448, "hp": 382},special:{"id": "sukunaVessel", "desc": "When below 50% HP: +25% ATK and +15% DEF simultaneously"}},
  {id:'chest_030',name:'Void Core Plate',rarity:'mythic',slot:'chest',desc:'Contains the compressed energy of a collapsed dimension.',lore:'A dimension died so this armor could exist.',stats:{"def": 500, "hp": 365},special:{"id": "voidCore", "desc": "Each turn you survive: gain +2% DEF stacking (max 20% this battle)"}},
  {id:'boot_001',name:'Iron Greaves',rarity:'common',slot:'boot',desc:'Standard dungeon footwear. Heavy and reliable.',lore:'Your feet carry you further than your willpower does.',stats:{"speed": 5, "def": 10},special:null},
  {id:'boot_002',name:'Leather Boots',rarity:'common',slot:'boot',desc:'Light and flexible. Good for moving fast.',lore:'Speed saves more lives than armor.',stats:{"speed": 8, "def": 7},special:null},
  {id:'boot_003',name:'Scout Runners',rarity:'common',slot:'boot',desc:'Designed for speed over protection.',lore:'First in. First out. That\'s the plan.',stats:{"speed": 10, "def": 5},special:null},
  {id:'boot_004',name:'Stone Grip Sabatons',rarity:'common',slot:'boot',desc:'Extra grip on stone dungeon surfaces.',lore:'Slipping in a dungeon is fatal.',stats:{"speed": 5, "def": 11},special:null},
  {id:'boot_005',name:'Bandit Boots',rarity:'common',slot:'boot',desc:'Silent soles. Perfect for dark dungeons.',lore:'Sound is a liability. These eliminate it.',stats:{"speed": 10, "def": 5},special:null},
  {id:'boot_006',name:'Shadow Step Boots',rarity:'uncommon',slot:'boot',desc:'Muffles footsteps completely in dark dungeons.',lore:'The best assassins make no sound at all.',stats:{"speed": 16, "def": 18},special:null},
  {id:'boot_007',name:'Windrunner Boots',rarity:'uncommon',slot:'boot',desc:'Wind mana channels through the soles.',lore:'Every step carries a tailwind.',stats:{"speed": 20, "def": 14},special:null},
  {id:'boot_008',name:'Runebound Boots',rarity:'uncommon',slot:'boot',desc:'Speed runes inscribed on the soles.',lore:'Ancient hunters knew the value of the first step.',stats:{"speed": 16, "def": 18},special:null},
  {id:'boot_009',name:'Storm Rider Boots',rarity:'uncommon',slot:'boot',desc:'Built for the fastest dungeon speed runs.',lore:'When you move this fast, DEF matters less.',stats:{"speed": 21, "def": 13},special:null},
  {id:'boot_010',name:'Reaper\'s Boots',rarity:'uncommon',slot:'boot',desc:'Jet black. No sound. No trace.',lore:'You were there. Then you weren\'t.',stats:{"speed": 18, "def": 16},special:null},
  {id:'boot_011',name:'Dragon Claw Greaves',rarity:'rare',slot:'boot',desc:'Reinforced with dragon claw material at the toes.',lore:'The dragon moved fast. So do you now.',stats:{"speed": 28, "def": 32},special:null},
  {id:'boot_012',name:'Igris Shadow Boots',rarity:'rare',slot:'boot',desc:'The Shadow Knight\'s own boots. Never slow.',lore:'Igris\'s loyalty is matched only by his speed.',stats:{"speed": 30, "def": 30},special:null},
  {id:'boot_013',name:'Tempest Runners',rarity:'rare',slot:'boot',desc:'Wind mana flows from every step.',lore:'The dungeon floor becomes a runway.',stats:{"speed": 33, "def": 28},special:null},
  {id:'boot_014',name:'Flash Step Boots',rarity:'rare',slot:'boot',desc:'Inspired by the Soul Society\'s fastest shinigami.',lore:'One step. Three positions. Pick one.',stats:{"speed": 35, "def": 26},special:null},
  {id:'boot_015',name:'Void Step Boots',rarity:'rare',slot:'boot',desc:'Briefly interact with the void layer on each step.',lore:'Every step is a small miracle of physics.',stats:{"speed": 32, "def": 28},special:null},
  {id:'boot_016',name:'Shadow Stride Boots',rarity:'epic',slot:'boot',desc:'High-rank shadow soldier boots. Unnaturally fast.',lore:'The Shadow Monarch\'s army appears out of nowhere.',stats:{"speed": 48, "def": 52},special:null},
  {id:'boot_017',name:'Shunpo Boots',rarity:'epic',slot:'boot',desc:'Soul Reaper flash-step compressed into dungeon boots.',lore:'There. Then there. Then somewhere you didn\'t expect.',stats:{"speed": 55, "def": 45},special:null},
  {id:'boot_018',name:'Eight Gates Boots',rarity:'epic',slot:'boot',desc:'Inspired by the Eight Gates physical release.',lore:'The body opens. Power pours out.',stats:{"speed": 54, "def": 46},special:null},
  {id:'boot_019',name:'Limitless Step Boots',rarity:'epic',slot:'boot',desc:'Channels the Limitless at the foot level.',lore:'Blue projected forward. Every step accelerated.',stats:{"speed": 46, "def": 54},special:null},
  {id:'boot_020',name:'Titan Stomp Boots',rarity:'epic',slot:'boot',desc:'Reinforced titan bone. Shakes the ground on contact.',lore:'Speed and weight. An unstoppable combination.',stats:{"speed": 44, "def": 57},special:null},
  {id:'boot_021',name:'Absolute Speed Boots',rarity:'legendary',slot:'boot',desc:'Passively enhances movement beyond measured limits.',lore:'The stopwatch gave up trying to track it.',stats:{"speed": 90, "def": 80},special:{"id": "velocityBurst", "desc": "First action each battle has +20% accuracy and cannot be dodged"}},
  {id:'boot_022',name:'Igris\'s True Boots',rarity:'legendary',slot:'boot',desc:'The boots Igris wore before becoming a shadow soldier.',lore:'He walked into the Shadow Monarch\'s service. These carried him.',stats:{"speed": 95, "def": 78},special:{"id": "loyalCharge", "desc": "First strike chance +30% on every dungeon floor"}},
  {id:'boot_023',name:'Muzan\'s Blood Steps',rarity:'legendary',slot:'boot',desc:'The demon king moved so fast no blade tracked him.',lore:'No one saw him move. Just the aftermath.',stats:{"speed": 96, "def": 77},special:{"id": "bloodStep", "desc": "Automatically dodge the first basic attack of each battle"}},
  {id:'boot_024',name:'Dragon King\'s Boots',rarity:'legendary',slot:'boot',desc:'The Dragon Monarch moved like lightning.',lore:'He was lightning. These are what he left behind.',stats:{"speed": 94, "def": 78},special:{"id": "dragonStep", "desc": "After dodging: next attack deals +25% damage"}},
  {id:'boot_025',name:'National Level Boots',rarity:'legendary',slot:'boot',desc:'Worn by hunters who move faster than armies react.',lore:'By the time the order is given, he\'s already there.',stats:{"speed": 100, "def": 75},special:{"id": "nationalSpeed", "desc": "First action every battle cannot be interrupted or countered"}},
  {id:'boot_026',name:'Shadow Monarch\'s True Boots',rarity:'mythic',slot:'boot',desc:'Sung Jinwoo\'s boots. Faster than perception itself.',lore:'He walked into the dungeon. The dungeon blinked. He was already out.',stats:{"speed": 180, "def": 150},special:{"id": "monarchSpeed", "desc": "Cannot be dodged by enemies. Your first action each battle is guaranteed to hit"}},
  {id:'boot_027',name:'Architect\'s Stride',rarity:'mythic',slot:'boot',desc:'The Architect moves between systems. These allow it.',lore:'Systems don\'t move. He does.',stats:{"speed": 175, "def": 155},special:{"id": "systemStride", "desc": "Teleport behind enemy once per battle \u2014 next attack is a guaranteed crit"}},
  {id:'boot_028',name:'Absolute Being\'s Steps',rarity:'mythic',slot:'boot',desc:'The divine\'s movement transcends physics entirely.',lore:'Physics describes movement. This transcends physics.',stats:{"speed": 185, "def": 148},special:{"id": "absoluteStep", "desc": "Immune to all movement-reducing effects. +30% dodge chance"}},
  {id:'boot_029',name:'Sukuna\'s True Step',rarity:'mythic',slot:'boot',desc:'The King of Curses moves before you think to attack.',lore:'He reacts to what hasn\'t happened yet.',stats:{"speed": 178, "def": 152},special:{"id": "reverseStep", "desc": "20% chance to completely ignore any incoming attack"}},
  {id:'boot_030',name:'Void Throne Boots',rarity:'mythic',slot:'boot',desc:'Worn by the being who built the gate network.',lore:'He walked between dimensions. You\'ll settle for dungeons.',stats:{"speed": 200, "def": 140},special:{"id": "voidWalk", "desc": "Immune to all crowd control \u2014 cannot be stunned, frozen, slowed, or feared"}},
  {id:'cloak_001',name:'Dungeon Cloth Cloak',rarity:'common',slot:'cloak',desc:'Basic protection against dungeon elements.',lore:'Thin but better than exposed.',stats:{"evasion": 3, "statusResist": 4},special:null},
  {id:'cloak_002',name:'Leather Cape',rarity:'common',slot:'cloak',desc:'Simple leather. Turns wind and minor attacks.',lore:'Wind is an enemy too.',stats:{"evasion": 4, "statusResist": 3},special:null},
  {id:'cloak_003',name:'Traveler\'s Cloak',rarity:'common',slot:'cloak',desc:'Reinforced for rough dungeon terrain.',lore:'Miles of dungeon in every thread.',stats:{"evasion": 4, "statusResist": 4},special:null},
  {id:'cloak_004',name:'Bandit\'s Cloak',rarity:'common',slot:'cloak',desc:'Dark colored. Hard to see against dungeon walls.',lore:'Blending in is the bandit\'s first skill.',stats:{"evasion": 5, "statusResist": 3},special:null},
  {id:'cloak_005',name:'Holy Mantle',rarity:'common',slot:'cloak',desc:'Marked with a faded holy symbol.',lore:'The blessing faded. The cloth didn\'t.',stats:{"evasion": 3, "statusResist": 6},special:null},
  {id:'cloak_006',name:'Shadow Weave Cloak',rarity:'uncommon',slot:'cloak',desc:'Woven from shadow dungeon material. Hard to see.',lore:'Darkness made wearable.',stats:{"evasion": 10, "statusResist": 10},special:null},
  {id:'cloak_007',name:'Flame Warden Cape',rarity:'uncommon',slot:'cloak',desc:'Fire-treated cloth. Repels minor fire attacks.',lore:'Some dungeons run hot. Be ready.',stats:{"evasion": 8, "statusResist": 12},special:null},
  {id:'cloak_008',name:'Twilight Cloak',rarity:'uncommon',slot:'cloak',desc:'Dark. Silent. Blends into dungeon shadows perfectly.',lore:'Night is not the enemy when you are the night.',stats:{"evasion": 12, "statusResist": 9},special:null},
  {id:'cloak_009',name:'Ghost Silk Cloak',rarity:'uncommon',slot:'cloak',desc:'Ghost dungeon silk. Nearly invisible.',lore:'Wear nothing. Be nothing. Survive everything.',stats:{"evasion": 13, "statusResist": 8},special:null},
  {id:'cloak_010',name:'Reaper\'s Cloak',rarity:'uncommon',slot:'cloak',desc:'Jet black. Absorbs dungeon ambient energy.',lore:'The reaper doesn\'t announce himself.',stats:{"evasion": 11, "statusResist": 10},special:null},
  {id:'cloak_011',name:'Dragon Wing Cape',rarity:'rare',slot:'cloak',desc:'Made from a dragon-type boss wing membrane.',lore:'Dragons fly. You evade. Same principle.',stats:{"evasion": 20, "statusResist": 18},special:null},
  {id:'cloak_012',name:'Igris Shadow Cloak',rarity:'rare',slot:'cloak',desc:'The Shadow Knight\'s own mantle.',lore:'Loyalty is its own armor.',stats:{"evasion": 22, "statusResist": 17},special:null},
  {id:'cloak_013',name:'Tempest Cloak',rarity:'rare',slot:'cloak',desc:'Wind mana saturated. Deflects weaker attacks.',lore:'The wind decides what reaches you.',stats:{"evasion": 24, "statusResist": 16},special:null},
  {id:'cloak_014',name:'Haori of Elements',rarity:'rare',slot:'cloak',desc:'Designed after the Flame Hashira\'s haori.',lore:'The flame pattern isn\'t decorative.',stats:{"evasion": 20, "statusResist": 20},special:null},
  {id:'cloak_015',name:'Specter Shroud',rarity:'rare',slot:'cloak',desc:'Partial intangibility from shadow mana infusion.',lore:'Half here. Half gone. Attacks find the wrong half.',stats:{"evasion": 25, "statusResist": 16},special:null},
  {id:'cloak_016',name:'Shadow Army Mantle',rarity:'epic',slot:'cloak',desc:'Worn by high-rank shadow soldiers of the Monarch.',lore:'The shadow army moves unseen. This cloak helps.',stats:{"evasion": 38, "statusResist": 32},special:null},
  {id:'cloak_017',name:'Infinity Shroud',rarity:'epic',slot:'cloak',desc:'The defensive principle of Infinity applied as fabric.',lore:'Attack it. It hasn\'t decided to let you through yet.',stats:{"evasion": 36, "statusResist": 34},special:null},
  {id:'cloak_018',name:'Soul Reaper Haori',rarity:'epic',slot:'cloak',desc:'A captain-class haori with battle reiatsu sealed inside.',lore:'Captain-level protection. Captain-level demands.',stats:{"evasion": 37, "statusResist": 33},special:null},
  {id:'cloak_019',name:'Akatsuki Cloak',rarity:'epic',slot:'cloak',desc:'The iconic red cloud cloak. Reinforced inside.',lore:'They were S-rank criminals. The cloaks were A-rank gear.',stats:{"evasion": 38, "statusResist": 32},special:null},
  {id:'cloak_020',name:'Titan Skin Mantle',rarity:'epic',slot:'cloak',desc:'Hardened titan skin, reshaped as a cloak.',lore:'The titans were invincible. This piece explains why.',stats:{"evasion": 36, "statusResist": 34},special:null},
  {id:'cloak_021',name:'Absolute Void Shroud',rarity:'legendary',slot:'cloak',desc:'Pulls attacks into a localized void pocket.',lore:'The attacks land nowhere. Literally.',stats:{"evasion": 70, "statusResist": 58},special:{"id": "voidAbsorb", "desc": "10% chance any attack is fully absorbed into void"}},
  {id:'cloak_022',name:'Igris\'s True Cloak',rarity:'legendary',slot:'cloak',desc:'The Shadow Knight\'s actual battle cloak.',lore:'He wore this when he served. Then when he fell. Then when he rose.',stats:{"evasion": 74, "statusResist": 55},special:{"id": "knightVow", "desc": "When an ally would die: absorb 30% of that damage yourself instead"}},
  {id:'cloak_023',name:'Muzan\'s Adaptive Cloak',rarity:'legendary',slot:'cloak',desc:'Shifts form to counter incoming attack types.',lore:'The demon king adapted. This adapts for you.',stats:{"evasion": 73, "statusResist": 56},special:{"id": "adaptiveShift", "desc": "After taking a hit: gain +5% resistance to that attack type (stacks 3x)"}},
  {id:'cloak_024',name:'Dragon King\'s Wing Cloak',rarity:'legendary',slot:'cloak',desc:'The Dragon Monarch\'s wing membrane, worn as a cloak.',lore:'Wings large enough to shadow a city. Now protecting one hunter.',stats:{"evasion": 74, "statusResist": 55},special:{"id": "dragonWing", "desc": "30% chance to halve incoming damage"}},
  {id:'cloak_025',name:'National Level Shroud',rarity:'legendary',slot:'cloak',desc:'Worn by hunters so powerful attacks rarely reach them.',lore:'At National Level, enemies hesitate. Hesitation is survival.',stats:{"evasion": 78, "statusResist": 53},special:{"id": "nationalPresence", "desc": "Enemies have -20% accuracy against you"}},
  {id:'cloak_026',name:'Shadow Monarch\'s True Cloak',rarity:'mythic',slot:'cloak',desc:'Sung Jinwoo\'s personal shadow cloak.',lore:'The Shadow Monarch doesn\'t need to dodge. He chooses to.',stats:{"evasion": 140, "statusResist": 110},special:{"id": "shadowCloak", "desc": "Immune to all status effects. 15% chance to fully negate any attack"}},
  {id:'cloak_027',name:'Architect\'s Observation Cloak',rarity:'mythic',slot:'cloak',desc:'The Architect observes but is never observed.',lore:'The watcher cannot be watched.',stats:{"evasion": 135, "statusResist": 115},special:{"id": "observer", "desc": "Cannot be targeted by enemy debuffs or status effects"}},
  {id:'cloak_028',name:'Absolute Being\'s Veil',rarity:'mythic',slot:'cloak',desc:'The divine\'s cloak — reality warps around it.',lore:'It doesn\'t protect. It redefines protection.',stats:{"evasion": 145, "statusResist": 108},special:{"id": "absoluteVeil", "desc": "Immune to all debuffs. Reduce all damage taken by 15%"}},
  {id:'cloak_029',name:'Sukuna\'s Domain Cloak',rarity:'mythic',slot:'cloak',desc:'The King of Curses\' personal domain shroud.',lore:'Inside his domain nothing escapes. Outside it, you do.',stats:{"evasion": 138, "statusResist": 112},special:{"id": "trueDomain", "desc": "Immune to Fear, Blind, Silence, and Paralyze. +20% evasion"}},
  {id:'cloak_030',name:'Void Throne Shroud',rarity:'mythic',slot:'cloak',desc:'The cloak worn by the creator of the gate system.',lore:'What created the gates wears something the gates cannot touch.',stats:{"evasion": 155, "statusResist": 102},special:{"id": "voidThroneShroud", "desc": "All status effects applied to you have 50% chance to fail completely"}},
  {id:'vam_001',name:'Iron Vambrace',rarity:'common',slot:'vam',desc:'Basic forearm guard. Stops glancing hits.',lore:'Where most blows land first.',stats:{"atk": 8, "crit": 2},special:null},
  {id:'vam_002',name:'Leather Arm Guard',rarity:'common',slot:'vam',desc:'Light and flexible dungeon wear.',lore:'Speed in the arm means speed in the strike.',stats:{"atk": 6, "crit": 3},special:null},
  {id:'vam_003',name:'Brawler\'s Wrap',rarity:'common',slot:'vam',desc:'Cloth wrap reinforced with dungeon ore strips.',lore:'Bare hands are braver. Guards are smarter.',stats:{"atk": 8, "crit": 2},special:null},
  {id:'vam_004',name:'Bone Shard Bracer',rarity:'common',slot:'vam',desc:'Skeleton-type creature bones sewn into the forearm.',lore:'Old bones. New hits.',stats:{"atk": 8, "crit": 2},special:null},
  {id:'vam_005',name:'Wolf Claw Bracer',rarity:'common',slot:'vam',desc:'Wolf claws attached to the knuckle guard.',lore:'The wolf\'s weapons become yours.',stats:{"atk": 8, "crit": 2},special:null},
  {id:'vam_006',name:'Shadow Strike Bracer',rarity:'uncommon',slot:'vam',desc:'Channels shadow mana through the strike arm.',lore:'Hits in places armor doesn\'t cover.',stats:{"atk": 18, "crit": 7},special:null},
  {id:'vam_007',name:'Flame Strike Bracer',rarity:'uncommon',slot:'vam',desc:'Heat-treated. Punches carry minor burn energy.',lore:'The heat leaves something behind.',stats:{"atk": 18, "crit": 7},special:null},
  {id:'vam_008',name:'Runebound Strike Bracer',rarity:'uncommon',slot:'vam',desc:'ATK runes inscribed on the forearm.',lore:'Ancient hunters carved power into the hitting arm.',stats:{"atk": 19, "crit": 7},special:null},
  {id:'vam_009',name:'Windcutter Bracer',rarity:'uncommon',slot:'vam',desc:'Wind mana channels through every strike.',lore:'The wind sharpens the blow.',stats:{"atk": 16, "crit": 9},special:null},
  {id:'vam_010',name:'Reaper\'s Bracer',rarity:'uncommon',slot:'vam',desc:'Channeled with death-type dungeon energy.',lore:'What the reaper touches doesn\'t always survive.',stats:{"atk": 19, "crit": 7},special:null},
  {id:'vam_011',name:'Dragon Claw Bracer',rarity:'rare',slot:'vam',desc:'Dragon claw tips at the knuckle guard.',lore:'Drag those claws. Feel the difference.',stats:{"atk": 32, "crit": 12},special:null},
  {id:'vam_012',name:'Igris Strike Bracer',rarity:'rare',slot:'vam',desc:'The Shadow Knight\'s sword arm bracer.',lore:'Igris\'s arm was his most dangerous weapon.',stats:{"atk": 35, "crit": 11},special:null},
  {id:'vam_013',name:'Tempest Fist Bracer',rarity:'rare',slot:'vam',desc:'Wind mana explodes from the punch on impact.',lore:'The hit arrives. Then the wind follows.',stats:{"atk": 30, "crit": 14},special:null},
  {id:'vam_014',name:'Nichirin Bracer',rarity:'rare',slot:'vam',desc:'Forged in the style of a Demon Slayer bracer.',lore:'The sun itself is sealed into the striking surface.',stats:{"atk": 32, "crit": 13},special:null},
  {id:'vam_015',name:'Void Strike Bracer',rarity:'rare',slot:'vam',desc:'Hits carry void energy that disrupts defenses.',lore:'The void doesn\'t defend. Neither does what you hit.',stats:{"atk": 32, "crit": 13},special:null},
  {id:'vam_016',name:'Shadow Fist Bracer',rarity:'epic',slot:'vam',desc:'High-rank shadow soldier striking arm guard.',lore:'Shadow soldiers\' strikes pierce armor like paper.',stats:{"atk": 55, "crit": 20},special:null},
  {id:'vam_017',name:'Infinity Force Bracer',rarity:'epic',slot:'vam',desc:'The Limitless applied as kinetic energy in strikes.',lore:'The hit doesn\'t land. The space collapses.',stats:{"atk": 54, "crit": 21},special:null},
  {id:'vam_018',name:'Eight Gates Bracer',rarity:'epic',slot:'vam',desc:'Designed after the Eight Gates physical release.',lore:'The body opens. Power pours out. This focuses it.',stats:{"atk": 61, "crit": 18},special:null},
  {id:'vam_019',name:'Cursed Energy Bracer',rarity:'epic',slot:'vam',desc:'Fused with a special-grade cursed spirit\'s striking essence.',lore:'Cursed energy doesn\'t care about defense type.',stats:{"atk": 57, "crit": 20},special:null},
  {id:'vam_020',name:'Titan Fist Bracer',rarity:'epic',slot:'vam',desc:'Titan bone, reshaped as a striking bracer.',lore:'Titan punches leveled cities. This is the focused version.',stats:{"atk": 59, "crit": 18},special:null},
  {id:'vam_021',name:'Absolute Impact Bracer',rarity:'legendary',slot:'vam',desc:'Every strike carries an absolute concussive force.',lore:'Not a metaphor. Physically absolute.',stats:{"atk": 110, "crit": 32},special:{"id": "absoluteImpact", "desc": "Every 3rd hit stuns the target for 1 turn"}},
  {id:'vam_022',name:'Igris\'s True Bracer',rarity:'legendary',slot:'vam',desc:'The Shadow Knight\'s actual battle vambrace.',lore:'He served. He fell. His arm never stopped.',stats:{"atk": 118, "crit": 30},special:{"id": "knightStrike", "desc": "+20% ATK when fighting elite or boss enemies"}},
  {id:'vam_023',name:'Susanoo\'s Fist Bracer',rarity:'legendary',slot:'vam',desc:'The Susanoo\'s weapon arm, sealed into a bracer.',lore:'The ultimate Susanoo\'s punch ended mountains.',stats:{"atk": 120, "crit": 29},special:{"id": "susanooFist", "desc": "Critical hits deal +30% bonus damage"}},
  {id:'vam_024',name:'Sukuna\'s Fist Bracer',rarity:'legendary',slot:'vam',desc:'The Cursed King\'s own striking bracer.',lore:'He killed with a flick. The bracer focused mountains.',stats:{"atk": 119, "crit": 30},special:{"id": "cursedFist", "desc": "Skills that deal damage always crit on enemies below 30% HP"}},
  {id:'vam_025',name:'National Level Bracer',rarity:'legendary',slot:'vam',desc:'Worn by hunters classified as National Level threats.',lore:'Nations built armies against this arm. The arm won.',stats:{"atk": 126, "crit": 28},special:{"id": "nationalForce", "desc": "+15% ATK and +15% crit chance during boss battles"}},
  {id:'vam_026',name:'Shadow Monarch\'s True Bracer',rarity:'mythic',slot:'vam',desc:'Sung Jinwoo\'s personal striking bracer.',lore:'Every shadow in existence lends its force to this arm.',stats:{"atk": 240, "crit": 55},special:{"id": "monarchFist", "desc": "Basic attacks deal splash damage to nearby enemies. Crits silence target for 1 turn"}},
  {id:'vam_027',name:'Architect\'s Force Bracer',rarity:'mythic',slot:'vam',desc:'The Architect\'s will made physical.',lore:'The system doesn\'t miss. Neither does this.',stats:{"atk": 228, "crit": 57},special:{"id": "systemForce", "desc": "All attacks ignore evasion. Cannot miss"}},
  {id:'vam_028',name:'Absolute Being\'s Arm',rarity:'mythic',slot:'vam',desc:'Fragment of the divine\'s physical striking arm.',lore:'Gods strike once. Everything ends.',stats:{"atk": 252, "crit": 53},special:{"id": "divineFist", "desc": "Once per battle: one attack deals 300% of normal damage"}},
  {id:'vam_029',name:'Sukuna\'s True Fist',rarity:'mythic',slot:'vam',desc:'Ryomen Sukuna\'s actual battle bracer.',lore:'A thousand years of malice in every hit.',stats:{"atk": 240, "crit": 55},special:{"id": "sukunaFist", "desc": "Dismantle \u2014 every hit removes 2% of enemy max HP as true damage ignoring DEF"}},
  {id:'vam_030',name:'Void Throne Bracer',rarity:'mythic',slot:'vam',desc:'Worn by the creator of the gate network itself.',lore:'What built the gates can end what lives inside them.',stats:{"atk": 265, "crit": 50},special:{"id": "voidThroneFist", "desc": "Each turn you deal most damage: gain +10% ATK stacking. Resets each dungeon"}},
  {id:'ring_001',name:'Iron Band',rarity:'common',slot:'ring',desc:'A simple iron ring. Faint mana resonance.',lore:'The most basic of hunter tools.',stats:{"critDmg": 5},special:{"id": "ironWill", "desc": "Gain +2 HP when you land a basic attack"}},
  {id:'ring_002',name:'Bone Loop',rarity:'common',slot:'ring',desc:'Crafted from dungeon creature bone. Light and active.',lore:'Bone carries death mana. Useful for hunters.',stats:{"critDmg": 5},special:{"id": "deathTouch", "desc": "5% chance to apply Poison on basic attacks"}},
  {id:'ring_003',name:'Hunter\'s Token Ring',rarity:'common',slot:'ring',desc:'Given as proof of first dungeon completion.',lore:'The dungeon was cleared. The ring proves it.',stats:{"critDmg": 5},special:{"id": "firstBlood", "desc": "First attack of every dungeon deals +10% damage"}},
  {id:'ring_004',name:'Goblin Tooth Ring',rarity:'common',slot:'ring',desc:'A goblin\'s tooth wrapped in wire. Crude but mean.',lore:'Goblins bite. The ring bites back.',stats:{"critDmg": 5},special:{"id": "goblinBite", "desc": "10% chance to Weaken target on basic attack (1 turn)"}},
  {id:'ring_005',name:'Ash Ring',rarity:'common',slot:'ring',desc:'Carved from dungeon ash material. Strangely active.',lore:'What survived the fire is never as fragile as it appears.',stats:{"critDmg": 5},special:{"id": "ashTouch", "desc": "10% chance to inflict Burn on basic attacks (1 turn)"}},
  {id:'ring_006',name:'Shadow Signet',rarity:'uncommon',slot:'ring',desc:'Channels shadow mana. Increases hit precision.',lore:'Where darkness goes, accuracy follows.',stats:{"critDmg": 14},special:{"id": "shadowAim", "desc": "Hits have +10% accuracy"}},
  {id:'ring_007',name:'Flame Ring',rarity:'uncommon',slot:'ring',desc:'Warm to the touch. Pulses with fire energy.',lore:'The fire in the ring wants out.',stats:{"critDmg": 14},special:{"id": "flamePulse", "desc": "20% chance to inflict Burn on basic attacks (2 turns)"}},
  {id:'ring_008',name:'Blood Ring',rarity:'uncommon',slot:'ring',desc:'Forged with gate crisis blood iron. Old and potent.',lore:'Old blood. Old iron. New purpose.',stats:{"critDmg": 15},special:{"id": "bloodPact", "desc": "When below 50% HP: +15% ATK"}},
  {id:'ring_009',name:'Glacial Band',rarity:'uncommon',slot:'ring',desc:'Cold touch. Channels minor freeze energy.',lore:'Cold hands. Warm kills.',stats:{"critDmg": 13},special:{"id": "iceTouch", "desc": "20% chance to inflict Freeze on crit (1 turn)"}},
  {id:'ring_010',name:'Reaper\'s Ring',rarity:'uncommon',slot:'ring',desc:'Death energy concentrated into a ring.',lore:'Every dungeon has a reaper. Wear the ring.',stats:{"critDmg": 14},special:{"id": "reaperMark", "desc": "Enemies below 20% HP take +15% bonus damage from you"}},
  {id:'ring_011',name:'Dragon\'s Eye Ring',rarity:'rare',slot:'ring',desc:'A dragon eye crystal set into a dungeon ring.',lore:'The eye saw everything the dragon did. It still does.',stats:{"critDmg": 25},special:{"id": "dragonEye", "desc": "See critical hit opportunities \u2014 +20% crit chance"}},
  {id:'ring_012',name:'Shadow Soldier Signet',rarity:'rare',slot:'ring',desc:'Worn by Igris himself in the dungeon conquest.',lore:'The loyalty of the Shadow Knight, compressed.',stats:{"critDmg": 26},special:{"id": "shadowSoldier", "desc": "+15% damage to all attacks"}},
  {id:'ring_013',name:'Cerberus Fang Ring',rarity:'rare',slot:'ring',desc:'One of Cerberus\'s three-headed fangs, set in iron.',lore:'Three bites for the price of one hit.',stats:{"critDmg": 26},special:{"id": "cerberusBite", "desc": "Basic attacks have 20% chance to Poison and Bleed simultaneously"}},
  {id:'ring_014',name:'Tanjiro\'s Water Ring',rarity:'rare',slot:'ring',desc:'Designed after Water Breathing techniques.',lore:'Breath of Water, compressed into a ring.',stats:{"critDmg": 24},special:{"id": "waterRing", "desc": "Basic attacks flow in combos \u2014 3rd consecutive hit deals +30% damage"}},
  {id:'ring_015',name:'Void Signet',rarity:'rare',slot:'ring',desc:'A void-touched ring. Causes minor dimensional distortion.',lore:'Minor is relative when the void is involved.',stats:{"critDmg": 25},special:{"id": "voidDistort", "desc": "15% chance any hit deals double damage"}},
  {id:'ring_016',name:'Shadow Marshal\'s Ring',rarity:'epic',slot:'ring',desc:'Worn by the Shadow Army\'s highest general.',lore:'The shadows follow whoever wears this.',stats:{"critDmg": 42},special:{"id": "shadowMarshal", "desc": "Your party members deal +10% more damage"}},
  {id:'ring_017',name:'Limitless Ring',rarity:'epic',slot:'ring',desc:'Channels Gojo\'s Limitless principle into every hit.',lore:'Blue. Red. Purple. Pick your destruction.',stats:{"critDmg": 43},special:{"id": "limitlessRing", "desc": "Every 4th attack is an automatic critical hit"}},
  {id:'ring_018',name:'Beru\'s Authority Ring',rarity:'epic',slot:'ring',desc:'A ring that carries the Ant King\'s commanding mana.',lore:'Beru commanded armies. The ring carries that authority.',stats:{"critDmg": 45},special:{"id": "antKingCommand", "desc": "Party members gain +5% ATK when you crit"}},
  {id:'ring_019',name:'Moonrend Ring',rarity:'epic',slot:'ring',desc:'Slices through defenses under moonlight.',lore:'The moon cuts as deep as any blade.',stats:{"critDmg": 43},special:{"id": "moonrend", "desc": "In dark dungeons or at night: crits ignore 30% DEF"}},
  {id:'ring_020',name:'Chaos Ring',rarity:'epic',slot:'ring',desc:'Reality fractures around the finger that wears this.',lore:'Attacks that find a broken reality hit harder.',stats:{"critDmg": 44},special:{"id": "chaosRing", "desc": "15% chance any attack deals triple damage instead"}},
  {id:'ring_021',name:'Absolute Execution Ring',rarity:'legendary',slot:'ring',desc:'Triggers an execute threshold on weakened enemies.',lore:'The ring decides when enough is enough.',stats:{"critDmg": 75},special:{"id": "absExec", "desc": "Instantly kill enemies below 8% HP (does not work on bosses)"}},
  {id:'ring_022',name:'Igris\'s Oath Ring',rarity:'legendary',slot:'ring',desc:'Igris\'s personal oath ring. Carries his vow.',lore:'He swore to serve. The ring carries every battle since.',stats:{"critDmg": 78},special:{"id": "igrisOath", "desc": "When an ally falls: +30% ATK and +30% crit chance for 3 turns"}},
  {id:'ring_023',name:'Sukuna\'s Signet',rarity:'legendary',slot:'ring',desc:'One of Ryomen Sukuna\'s twenty fingers, set as a ring.',lore:'One finger. Enough to end most hunters. Worn anyway.',stats:{"critDmg": 80},special:{"id": "sukunaSignet", "desc": "Crits have 25% chance to inflict Cursed Wound \u2014 enemy takes +15% damage for 3 turns"}},
  {id:'ring_024',name:'Dragon King\'s Ring',rarity:'legendary',slot:'ring',desc:'The Dragon Monarch\'s personal signet.',lore:'Dragons swear fealty to whoever wears this. Temporarily.',stats:{"critDmg": 79},special:{"id": "dragonPact", "desc": "+25% damage to all fire and lightning skills"}},
  {id:'ring_025',name:'National Level Ring',rarity:'legendary',slot:'ring',desc:'Worn by hunters who changed the balance of nations.',lore:'Governments changed policy because of this ring\'s wearer.',stats:{"critDmg": 82},special:{"id": "nationalRing", "desc": "+25% crit damage. Boss fights: crits reduce boss ATK by 10% (stacks 3x)"}},
  {id:'ring_026',name:'Shadow Monarch\'s True Ring',rarity:'mythic',slot:'ring',desc:'Sung Jinwoo\'s ring. Commands all shadow soldiers.',lore:'Every shadow. Every soldier. Every dungeon. This ring.',stats:{"critDmg": 150},special:{"id": "shadowMonarchRing", "desc": "Summon 3 shadow soldiers at battle start \u2014 they attack with you each turn (10% your ATK each)"}},
  {id:'ring_027',name:'Architect\'s Design Ring',rarity:'mythic',slot:'ring',desc:'The Architect\'s own ring. Controls system functions.',lore:'He designed the system. This ring is the key.',stats:{"critDmg": 145},special:{"id": "architectDesign", "desc": "Once per battle: reset all skill cooldowns instantly"}},
  {id:'ring_028',name:'Absolute Being\'s Ring',rarity:'mythic',slot:'ring',desc:'Fragment of the divine\'s will, compressed into a ring.',lore:'The absolute being needed one ring. Here it is.',stats:{"critDmg": 155},special:{"id": "absoluteRing", "desc": "Your crits cannot be dodged or blocked. Crit damage +50% permanently"}},
  {id:'ring_029',name:'Sukuna\'s True Finger Ring',rarity:'mythic',slot:'ring',desc:'An actual finger of Ryomen Sukuna, set as a ring.',lore:'A thousand years of curses in one ring. Wear it anyway.',stats:{"critDmg": 150},special:{"id": "sukunaFinger", "desc": "Domain Expansion \u2014 once per battle: all your attacks auto-crit for 2 turns. Enemies cannot dodge"}},
  {id:'ring_030',name:'Void Throne Ring',rarity:'mythic',slot:'ring',desc:'Worn by the being who created the gates and the system.',lore:'To understand this ring is to understand why everything exists.',stats:{"critDmg": 165},special:{"id": "voidThroneRing", "desc": "Once per dungeon: Void Collapse \u2014 all enemies lose 25% of their current HP instantly. Cannot be resisted"}}
];


// ── Lookup helpers ──────────────────────────────────────────────
const CATALOG_BY_ID   = Object.fromEntries(GEAR_CATALOG.map(g => [g.id, g]));
const CATALOG_BY_SLOT = {};
const CATALOG_BY_RARITY = {};

for (const g of GEAR_CATALOG) {
  if (!CATALOG_BY_SLOT[g.slot])   CATALOG_BY_SLOT[g.slot]   = [];
  if (!CATALOG_BY_RARITY[g.rarity]) CATALOG_BY_RARITY[g.rarity] = [];
  CATALOG_BY_SLOT[g.slot].push(g);
  CATALOG_BY_RARITY[g.rarity].push(g);
}

const RARITY_ORDER = ['common','uncommon','rare','epic','legendary','mythic'];
const RARITY_EMOJI = {
  common:    '⚪',
  uncommon:  '🟢',
  rare:      '🔵',
  epic:      '🟣',
  legendary: '🟠',
  mythic:    '🌌',
};

/**
 * Get a random gear piece for a given slot and rarity.
 * Falls back to a random piece of that slot if rarity not found.
 */
function getRandomGear(slot, rarity) {
  const slotKey = slot === 'helmet' ? 'helm' : slot === 'chestplate' ? 'chest' : slot === 'vambrace' ? 'vam' : slot;
  const pool = (CATALOG_BY_SLOT[slotKey] || []).filter(g => !rarity || g.rarity === rarity);
  if (!pool.length) return null;
  return pool[Math.floor(Math.random() * pool.length)];
}

/**
 * Format a gear piece for display in chat.
 */
function formatGear(gear, durability, maxDurability) {
  if (!gear) return 'None';
  const emoji = RARITY_EMOJI[gear.rarity] || '⚪';
  const dur = durability !== undefined ? ` 🔧 ${durability}/${maxDurability}` : '';
  const statStr = Object.entries(gear.stats)
    .map(([k,v]) => `+${v} ${k}`)
    .join(', ');
  let out = `${emoji} *${gear.name}*${dur}\n`;
  out += `📖 ${gear.desc}\n`;
  out += `📊 ${statStr}`;
  if (gear.special) {
    out += `\n✨ *${gear.special.id}*: ${gear.special.desc}`;
  }
  return out;
}

module.exports = { GEAR_CATALOG, CATALOG_BY_ID, CATALOG_BY_SLOT, CATALOG_BY_RARITY, RARITY_ORDER, RARITY_EMOJI, getRandomGear, formatGear };
